---
- name: Install database packages
  dnf:
      state: present
      name:
      - postgresql-server
      - python3-psycopg2
      - acl

- name: Initialize PostgreSQL
  command: postgresql-setup initdb
  args:
      creates: /var/lib/pgsql/data/pg_hba.conf

- replace:
    dest: /var/lib/pgsql/data/pg_hba.conf
    regexp: "host    all             all             127.0.0.1/32            ident"
    replace: "host    all             all             127.0.0.1/32            trust"

- replace:
    dest: /var/lib/pgsql/data/pg_hba.conf
    regexp: "host    all             all             ::1/128                 ident"
    replace: "host    all             all             ::1/128                 trust"

- service:
    name: postgresql
    state: started
    enabled: yes

- block:
    - name: Create the database user
      postgresql_user:
        name: "mediawikiuser"

  become: yes
  become_user: postgres
  become_method: sudo

- name: Create the database itself
  postgresql_db:
    name: "mediawikidb"
    owner: "mediawikiuser"
    encoding: UTF-8
  become: yes
  become_user: postgres
  become_method: sudo

- name: Test the database creation
  postgresql_db:
    name: "mediawikidb"
    owner: "mediawikiuser"
    encoding: UTF-8
  become: yes
  become_user: postgres
  become_method: sudo
