---

- seboolean: name=httpd_can_network_connect_db state=yes persistent=yes

- seboolean: name=httpd_use_fusefs state=yes persistent=yes

- name: Install packages
  dnf:
      state: present
      name:
      - mediawiki
      - postgresql-devel
      - php-pgsql
      - php-intl
      - httpd

- name: Install the mediawiki.conf apache config file
  copy:
    src: mediawiki.conf
    dest: /etc/httpd/conf.d/mediawiki.conf
    owner: root
    group: root
    mode: '0644'

- service:
    name: httpd
    state: started
    enabled: yes

- name: setup mediawiki
  shell: php /usr/share/mediawiki/maintenance/install.php --server http://wiki.tinystage.test --scriptpath /w --dbuser mediawikiuser --confpath /usr/share/mediawiki --dbname mediawikidb --dbport 5432 --dbserver 127.0.0.1 --dbtype postgres --lang en --pass "@dminp@ssword" fedora admin
  args:
      creates: /usr/share/mediawiki/LocalSettings.php

- replace:
    dest: /usr/share/mediawiki/LocalSettings.php
    regexp: "vector-2022"
    replace: "fedora"

- lineinfile:
    dest: /usr/share/mediawiki/LocalSettings.php
    line: "# error_reporting( -1 );"
    state: present

- lineinfile:
    dest: /usr/share/mediawiki/LocalSettings.php
    line: "# ini_set( 'display_errors', 1 );"
    state: present
