---

- seboolean: name=httpd_can_network_connect_db state=yes persistent=yes

- seboolean: name=httpd_use_fusefs state=yes persistent=yes

- name: Install packages
  dnf:
      state: present
      name:
      - mediawiki
      - postgresql-devel
      - php-pgsql
      - httpd

- name: Install the mediawiki.conf apache config file
  copy:
    src: mediawiki.conf
    dest: /etc/httpd/conf.d/mediawiki.conf
    owner: root
    group: root
    mode: '0644'

- service:
    name: httpd
    state: started
    enabled: yes

- name: setup mediawiki
  shell: php /usr/share/mediawiki/maintenance/install.php --dbuser mediawikiuser --confpath /var/www/wiki --dbname mediawikidb --dbport 5432 --dbserver 127.0.0.1 --dbtype postgres --lang en --pass "password" fedora admin
  args:
      creates: /var/www/wiki/LocalSettings.php

- replace:
    dest: /var/www/wiki/LocalSettings.php
    regexp: "vector"
    replace: "fedora"

- name: copy logo
  shell: cp /usr/share/mediawiki/skins/Fedora/resources/images/fedorawiki_logo.png /usr/share/mediawiki/resources/assets/fedorawiki_logo.png
  args:
      creates: /usr/share/mediawiki/resources/assets/fedorawiki_logo.png

- replace:
    dest: /var/www/wiki/LocalSettings.php
    regexp: "wiki.png"
    replace: "fedorawiki_logo.png"

- lineinfile:
    dest: /var/www/wiki/LocalSettings.php
    line: "error_reporting( -1 );"
    state: present

- lineinfile:
    dest: /var/www/wiki/LocalSettings.php
    line: "ini_set( 'display_errors', 1 );"
    state: present
